data:
  data_dir: G:/joohyun/research/AutoPET Challenge 2024/data/train
  # data_dir_preprocessed: G:/joohyun/research/AutoPET Challenge 2024/preprocessed
  splits_file: G:/joohyun/research/AutoPET Challenge 2024/json/train_fold_final_psma_data.json
  fold: 0
  target_shape: [ 128, 160, 112 ]
  batch_size: 2
  suffix: .nii.gz
  num_workers_train: 3
  num_workers_val: 3

logger:
  experiment: lightning_logs
  name: train_fold_final_psma

model:
  pretrained: true
  resume: true
  ckpt_path: G:/joohyun/Github/datacentric/lightning_logs/train_fold_final_fdg/version_0/checkpoints/last.ckpt
  lr: 0.0001
  sw_batch_size: 4
  seed: 42

trainer:
  max_epochs: 250
  # max_steps: 100000
  check_val_every_n_epoch: 5
  precision: bf16-mixed #32, 16
  accelerator: gpu
  devices: 1
  deterministic: true
  strategy: auto
  sync_batchnorm: true #false
  log_every_n_steps: 10